// <auto-generated />
using System;
using MealPrepService.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealPrepService.DAL.Migrations
{
    [DbContext(typeof(MealPrepDbContext))]
    [Migration("20260126051758_AddMealEntity")]
    partial class AddMealEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MealPrepService.DAL.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("CaloriesPerServing")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("CarbsG")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContainsAllergens")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("FatG")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("FiberG")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<bool>("GoodForMaintain")
                        .HasColumnType("bit");

                    b.Property<bool>("GoodForMuscleGain")
                        .HasColumnType("bit");

                    b.Property<bool>("GoodForWeightLoss")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDairyFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<double>("ProteinG")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Cuisine");

                    b.HasIndex("IsActive");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = "Medium",
                            CaloriesPerServing = 450.0,
                            CarbsG = 55.0,
                            Category = "Breakfast",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1686),
                            Cuisine = "Vietnamese",
                            Description = "Phở bò với nước dùng thơm ngon, bánh phở tươi và thịt bò tái",
                            DifficultyLevel = "Medium",
                            FatG = 12.0,
                            FiberG = 3.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = false,
                            ImagePath = "/images/pho-bo.jpg",
                            Ingredients = "Bánh phở, thịt bò, hành tây, gừng, quế, hồi, muối, nước mắm",
                            Instructions = "Ninh xương bò 3-4h, thái thịt bò mỏng, trụng bánh phở, múc nước dùng và cho thịt tái lên trên",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Phở Bò Truyền Thống",
                            PrepTimeMinutes = 45,
                            ProteinG = 25.0,
                            Tags = "traditional,vietnamese,high-protein"
                        },
                        new
                        {
                            Id = 2,
                            Budget = "Low",
                            CaloriesPerServing = 380.0,
                            CarbsG = 45.0,
                            Category = "Breakfast",
                            ContainsAllergens = "Gluten",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1691),
                            Cuisine = "Vietnamese",
                            Description = "Bánh mì giòn với thịt nướng thơm, rau sống và nước sốt đặc biệt",
                            DifficultyLevel = "Easy",
                            FatG = 15.0,
                            FiberG = 4.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = false,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/banh-mi.jpg",
                            Ingredients = "Bánh mì, thịt heo nướng, dưa chuột, rau thơm, tương ớt",
                            Instructions = "Nướng thịt, cắt bánh mì, kẹp thịt và rau vào bánh mì",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = false,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Bánh Mì Thịt Nướng",
                            PrepTimeMinutes = 20,
                            ProteinG = 18.0,
                            Tags = "quick,portable,vietnamese"
                        },
                        new
                        {
                            Id = 3,
                            Budget = "Medium",
                            CaloriesPerServing = 320.0,
                            CarbsG = 58.0,
                            Category = "Breakfast",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1695),
                            Cuisine = "Western",
                            Description = "Yến mạch bổ dưỡng với các loại berry tươi và hạt",
                            DifficultyLevel = "Easy",
                            FatG = 8.0,
                            FiberG = 10.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = false,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/oatmeal-berry.jpg",
                            Ingredients = "Yến mạch, sữa hạnh nhân, blueberry, strawberry, hạt chia, mật ong",
                            Instructions = "Nấu yến mạch với sữa hạnh nhân, cho berry và hạt chia lên trên",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            Name = "Oatmeal với Berry",
                            PrepTimeMinutes = 10,
                            ProteinG = 12.0,
                            Tags = "healthy,high-fiber,vegetarian"
                        },
                        new
                        {
                            Id = 4,
                            Budget = "Low",
                            CaloriesPerServing = 280.0,
                            CarbsG = 15.0,
                            Category = "Breakfast",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1698),
                            Cuisine = "Asian",
                            Description = "Trứng chiên với nhiều loại rau củ bổ dưỡng",
                            DifficultyLevel = "Easy",
                            FatG = 18.0,
                            FiberG = 5.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/egg-veggie.jpg",
                            Ingredients = "Trứng gà, cà rốt, đậu cove, hành tây, tỏi, dầu ăn",
                            Instructions = "Xào rau củ, đánh trứng và chiên cùng rau",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Trứng Chiên Rau Củ",
                            PrepTimeMinutes = 15,
                            ProteinG = 20.0,
                            Tags = "high-protein,vegetarian,low-carb"
                        },
                        new
                        {
                            Id = 5,
                            Budget = "Medium",
                            CaloriesPerServing = 180.0,
                            CarbsG = 35.0,
                            Category = "Breakfast",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1702),
                            Cuisine = "Western",
                            Description = "Sinh tố xanh giàu vitamin và chất xơ",
                            DifficultyLevel = "Easy",
                            FatG = 4.0,
                            FiberG = 8.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = false,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/green-smoothie.jpg",
                            Ingredients = "Rau bina, chuối, táo xanh, gừng, chanh, nước dừa",
                            Instructions = "Cho tất cả vào máy xay, xay nhuyễn và thưởng thức",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            Name = "Smoothie Xanh Detox",
                            PrepTimeMinutes = 5,
                            ProteinG = 8.0,
                            Tags = "detox,low-calorie,vegan"
                        },
                        new
                        {
                            Id = 6,
                            Budget = "Medium",
                            CaloriesPerServing = 520.0,
                            CarbsG = 65.0,
                            Category = "Lunch",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1705),
                            Cuisine = "Vietnamese",
                            Description = "Cơm trắng với gà nướng sả thơm lừng",
                            DifficultyLevel = "Medium",
                            FatG = 12.0,
                            FiberG = 3.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = false,
                            ImagePath = "/images/com-ga-nuong.jpg",
                            Ingredients = "Thịt gà, sả, tỏi, gia vị, cơm trắng, rau sống",
                            Instructions = "Ướp gà với sả và gia vị, nướng chín, ăn kèm cơm và rau",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Cơm Gà Nướng Lemongrass",
                            PrepTimeMinutes = 40,
                            ProteinG = 35.0,
                            Tags = "high-protein,vietnamese,balanced"
                        },
                        new
                        {
                            Id = 7,
                            Budget = "High",
                            CaloriesPerServing = 420.0,
                            CarbsG = 35.0,
                            Category = "Lunch",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1709),
                            Cuisine = "Western",
                            Description = "Salad gà nướng với quinoa và rau xanh",
                            DifficultyLevel = "Easy",
                            FatG = 18.0,
                            FiberG = 8.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/chicken-quinoa-salad.jpg",
                            Ingredients = "Thịt gà, quinoa, rau xà lách, cà chua, dưa chuột, dressing olive oil",
                            Instructions = "Nấu quinoa, nướng gà, trộn salad với dressing",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Salad Gà Quinoa",
                            PrepTimeMinutes = 25,
                            ProteinG = 30.0,
                            Tags = "superfood,high-protein,low-calorie"
                        },
                        new
                        {
                            Id = 8,
                            Budget = "Medium",
                            CaloriesPerServing = 380.0,
                            CarbsG = 55.0,
                            Category = "Lunch",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1712),
                            Cuisine = "Asian",
                            Description = "Pad Thai chay với đậu hũ và rau củ",
                            DifficultyLevel = "Medium",
                            FatG = 12.0,
                            FiberG = 6.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = false,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/pad-thai-chay.jpg",
                            Ingredients = "Bánh phở khô, đậu hũ, giá đỗ, cà rốt, tương ớt chay",
                            Instructions = "Xào đậu hũ, trụng bánh phở, xào chung với rau và gia vị",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            Name = "Pad Thai Chay",
                            PrepTimeMinutes = 30,
                            ProteinG = 15.0,
                            Tags = "vegetarian,asian,balanced"
                        },
                        new
                        {
                            Id = 9,
                            Budget = "High",
                            CaloriesPerServing = 480.0,
                            CarbsG = 25.0,
                            Category = "Dinner",
                            ContainsAllergens = "Soy,Gluten",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1716),
                            Cuisine = "Asian",
                            Description = "Cá hồi nướng với sốt teriyaki và rau củ",
                            DifficultyLevel = "Medium",
                            FatG = 25.0,
                            FiberG = 4.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = false,
                            ImagePath = "/images/salmon-teriyaki.jpg",
                            Ingredients = "Cá hồi, sốt teriyaki, súp lơ xanh, cà rốt, gạo lứt",
                            Instructions = "Ướp cá với sốt teriyaki, nướng cá, hấp rau củ",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = false,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Cá Hồi Nướng Teriyaki",
                            PrepTimeMinutes = 35,
                            ProteinG = 40.0,
                            Tags = "omega-3,high-protein,premium"
                        },
                        new
                        {
                            Id = 10,
                            Budget = "High",
                            CaloriesPerServing = 550.0,
                            CarbsG = 35.0,
                            Category = "Dinner",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1719),
                            Cuisine = "Vietnamese",
                            Description = "Thịt bò thăn xào với khoai tây và rau củ",
                            DifficultyLevel = "Medium",
                            FatG = 28.0,
                            FiberG = 5.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = false,
                            ImagePath = "/images/bo-luc-lac.jpg",
                            Ingredients = "Thịt bò thăn, khoai tây, hành tây, tiêu đen, tỏi",
                            Instructions = "Thái thịt bò hạt lựu, ướp gia vị, xào nhanh tay",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Thịt Bò Xào Lúc Lắc",
                            PrepTimeMinutes = 30,
                            ProteinG = 38.0,
                            Tags = "high-protein,vietnamese,premium"
                        },
                        new
                        {
                            Id = 11,
                            Budget = "Medium",
                            CaloriesPerServing = 220.0,
                            CarbsG = 18.0,
                            Category = "Snack",
                            ContainsAllergens = "Dairy,Nuts",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1723),
                            Cuisine = "Western",
                            Description = "Sữa chua Hy Lạp với hạt điều và mật ong",
                            DifficultyLevel = "Easy",
                            FatG = 12.0,
                            FiberG = 3.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/greek-yogurt.jpg",
                            Ingredients = "Greek yogurt, hạt điều, mật ong, quế bột",
                            Instructions = "Trộn tất cả các nguyên liệu với nhau",
                            IsActive = true,
                            IsDairyFree = false,
                            IsGlutenFree = true,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Greek Yogurt Hạt Điều",
                            PrepTimeMinutes = 5,
                            ProteinG = 15.0,
                            Tags = "high-protein,quick,healthy"
                        },
                        new
                        {
                            Id = 12,
                            Budget = "Medium",
                            CaloriesPerServing = 180.0,
                            CarbsG = 20.0,
                            Category = "Snack",
                            ContainsAllergens = "Nuts",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1728),
                            Cuisine = "Western",
                            Description = "Hỗn hợp hạt và trái cây khô bổ dưỡng",
                            DifficultyLevel = "Easy",
                            FatG = 10.0,
                            FiberG = 4.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = false,
                            ImagePath = "/images/trail-mix.jpg",
                            Ingredients = "Hạnh nhân, nho khô, hạt điều, hạt bí ngô",
                            Instructions = "Trộn tất cả các loại hạt và trái cây khô",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            Name = "Trail Mix Energy",
                            PrepTimeMinutes = 2,
                            ProteinG = 6.0,
                            Tags = "portable,energy,nuts"
                        },
                        new
                        {
                            Id = 13,
                            Budget = "Medium",
                            CaloriesPerServing = 480.0,
                            CarbsG = 60.0,
                            Category = "Lunch",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1731),
                            Cuisine = "Vietnamese",
                            Description = "Bún bò Huế truyền thống với nước dùng đậm đà",
                            DifficultyLevel = "Hard",
                            FatG = 15.0,
                            FiberG = 4.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = false,
                            ImagePath = "/images/bun-bo-hue.jpg",
                            Ingredients = "Bún tươi, thịt bò, chả cá, tôm khô, sả, tỏi, ớt",
                            Instructions = "Ninh xương bò, nấu nước dùng, trụng bún và cho topping",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Bún Bò Huế",
                            PrepTimeMinutes = 120,
                            ProteinG = 28.0,
                            Tags = "traditional,vietnamese,spicy"
                        },
                        new
                        {
                            Id = 14,
                            Budget = "Medium",
                            CaloriesPerServing = 380.0,
                            CarbsG = 45.0,
                            Category = "Lunch",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1735),
                            Cuisine = "Western",
                            Description = "Tô thức ăn chay đầy màu sắc và dinh dưỡng",
                            DifficultyLevel = "Easy",
                            FatG = 16.0,
                            FiberG = 12.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = false,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/buddha-bowl.jpg",
                            Ingredients = "Quinoa, cải kale, cà chua, bơ, đậu đen, hạt bí ngô",
                            Instructions = "Nấu quinoa, chuẩn bị các loại rau, xếp vào tô và thưởng thức",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            Name = "Buddha Bowl",
                            PrepTimeMinutes = 20,
                            ProteinG = 18.0,
                            Tags = "superfood,colorful,vegan"
                        },
                        new
                        {
                            Id = 15,
                            Budget = "Medium",
                            CaloriesPerServing = 350.0,
                            CarbsG = 40.0,
                            Category = "Breakfast",
                            ContainsAllergens = "Dairy",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1738),
                            Cuisine = "Western",
                            Description = "Bánh pancake protein cho bữa sáng bổ dưỡng",
                            DifficultyLevel = "Easy",
                            FatG = 10.0,
                            FiberG = 6.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/protein-pancakes.jpg",
                            Ingredients = "Protein powder, yến mạch, trứng, chuối, sữa tươi",
                            Instructions = "Xay nhuyễn tất cả, đổ vào chảo và chiên như pancake thông thường",
                            IsActive = true,
                            IsDairyFree = false,
                            IsGlutenFree = true,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Protein Pancakes",
                            PrepTimeMinutes = 15,
                            ProteinG = 25.0,
                            Tags = "high-protein,fitness,breakfast"
                        },
                        new
                        {
                            Id = 16,
                            Budget = "Medium",
                            CaloriesPerServing = 200.0,
                            CarbsG = 12.0,
                            Category = "Dinner",
                            ContainsAllergens = "Shellfish",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1742),
                            Cuisine = "Asian",
                            Description = "Canh chua cay Thái Lan với tôm tươi",
                            DifficultyLevel = "Medium",
                            FatG = 8.0,
                            FiberG = 3.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = false,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/tom-yum.jpg",
                            Ingredients = "Tôm tươi, sả, lá chanh, ớt, nấm, cà chua",
                            Instructions = "Nấu nước dùng với sả và lá chanh, cho tôm và rau vào nấu",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Tom Yum Goong",
                            PrepTimeMinutes = 25,
                            ProteinG = 20.0,
                            Tags = "low-calorie,thai,spicy"
                        },
                        new
                        {
                            Id = 17,
                            Budget = "Medium",
                            CaloriesPerServing = 150.0,
                            CarbsG = 20.0,
                            Category = "Snack",
                            ContainsAllergens = "Nuts",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1745),
                            Cuisine = "Western",
                            Description = "Viên năng lượng từ hạt và trái cây khô",
                            DifficultyLevel = "Easy",
                            FatG = 7.0,
                            FiberG = 4.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = false,
                            ImagePath = "/images/energy-balls.jpg",
                            Ingredients = "Chà là, hạnh nhân, hạt chia, bơ đậu phộng, bột ca cao",
                            Instructions = "Xay nhuyễn tất cả, vo thành từng viên nhỏ",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            Name = "Energy Balls",
                            PrepTimeMinutes = 10,
                            ProteinG = 5.0,
                            Tags = "raw,energy,portable"
                        },
                        new
                        {
                            Id = 18,
                            Budget = "Low",
                            CaloriesPerServing = 280.0,
                            CarbsG = 25.0,
                            Category = "Dinner",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1748),
                            Cuisine = "Asian",
                            Description = "Lẩu Thái chay với đậu hũ và rau củ",
                            DifficultyLevel = "Easy",
                            FatG = 12.0,
                            FiberG = 8.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = false,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/lau-thai-chay.jpg",
                            Ingredients = "Đậu hũ, nấm, bắp cải, cà rốt, sả, ớt, nước dùng chay",
                            Instructions = "Nấu nước dùng chay, cho rau củ và đậu hũ vào nấu",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            Name = "Lẩu Thái Chay",
                            PrepTimeMinutes = 20,
                            ProteinG = 15.0,
                            Tags = "vegetarian,thai,low-calorie"
                        },
                        new
                        {
                            Id = 19,
                            Budget = "Medium",
                            CaloriesPerServing = 250.0,
                            CarbsG = 25.0,
                            Category = "Breakfast",
                            ContainsAllergens = "",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1751),
                            Cuisine = "Western",
                            Description = "Pudding hạt chia với sữa dừa và trái cây",
                            DifficultyLevel = "Easy",
                            FatG = 15.0,
                            FiberG = 12.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = false,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/chia-pudding.jpg",
                            Ingredients = "Hạt chia, sữa dừa, mật ong, vanilla, mango",
                            Instructions = "Ngâm hạt chia qua đêm, cho topping trái cây",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            Name = "Chia Pudding",
                            PrepTimeMinutes = 5,
                            ProteinG = 8.0,
                            Tags = "superfood,overnight,high-fiber"
                        },
                        new
                        {
                            Id = 20,
                            Budget = "Medium",
                            CaloriesPerServing = 400.0,
                            CarbsG = 35.0,
                            Category = "Lunch",
                            ContainsAllergens = "Gluten",
                            CreatedAt = new DateTime(2026, 1, 26, 5, 17, 57, 105, DateTimeKind.Utc).AddTicks(1754),
                            Cuisine = "Western",
                            Description = "Bánh wrap gà nướng với rau xanh tươi mát",
                            DifficultyLevel = "Easy",
                            FatG = 16.0,
                            FiberG = 6.0,
                            GoodForMaintain = true,
                            GoodForMuscleGain = true,
                            GoodForWeightLoss = true,
                            ImagePath = "/images/chicken-wrap.jpg",
                            Ingredients = "Tortilla wrap, gà nướng, xà lách, cà chua, dưa chuột, avocado",
                            Instructions = "Nướng gà, chuẩn bị rau, cuốn vào tortilla",
                            IsActive = true,
                            IsDairyFree = true,
                            IsGlutenFree = false,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Grilled Chicken Wrap",
                            PrepTimeMinutes = 20,
                            ProteinG = 32.0,
                            Tags = "high-protein,portable,balanced"
                        });
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.MealReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrderId", "DayNumber", "MealType");

                    b.ToTable("MealReviews");
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.NutritionProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("BMR")
                        .HasColumnType("float");

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CuisinePreferences")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MealsPerDay")
                        .HasColumnType("int");

                    b.Property<double>("TDEE")
                        .HasColumnType("float");

                    b.Property<double>("TargetCalories")
                        .HasColumnType("float");

                    b.Property<double>("TargetCarbsG")
                        .HasColumnType("float");

                    b.Property<double>("TargetFatG")
                        .HasColumnType("float");

                    b.Property<double>("TargetProteinG")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("NutritionProfiles");
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<double>("CompletionPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MenuJsonData")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MenuPdfPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NutritionProfileId")
                        .HasColumnType("int");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NutritionProfileId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MealsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerWeek")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("HeightCm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.MealReview", b =>
                {
                    b.HasOne("MealPrepService.DAL.Entities.Order", "Order")
                        .WithMany("MealReviews")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPrepService.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.NutritionProfile", b =>
                {
                    b.HasOne("MealPrepService.DAL.Entities.User", "User")
                        .WithMany("NutritionProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.Order", b =>
                {
                    b.HasOne("MealPrepService.DAL.Entities.NutritionProfile", "NutritionProfile")
                        .WithMany("Orders")
                        .HasForeignKey("NutritionProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPrepService.DAL.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Orders")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPrepService.DAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NutritionProfile");

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.NutritionProfile", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.Order", b =>
                {
                    b.Navigation("MealReviews");
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MealPrepService.DAL.Entities.User", b =>
                {
                    b.Navigation("NutritionProfiles");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
